### ISSUE TITLE
Google Drive again... again....

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#21]
![chrome_SU3qc1zCeT](https://user-images.githubusercontent.com/13005453/180607351-04189a9e-3829-47a1-b706-1cb077b5e5fa.png)

Unselected items and text are all white only darkening when selected. Can't read item names. Also search text ("Search in Drive" bit is back against grey. Think the rest of it is just updated variables breaking things.

**Comment by blyad2137** [comment]
And done, that was a quick fix. I'll just fix Sheets and drop the update.
![image](https://user-images.githubusercontent.com/86572965/180618548-1fd11d30-8a08-47ae-821f-fe704c0aaa7b.png)

**Comment by C4J3** [comment]
Thanks so much! Small side note that the text in the search bar is black which though still visible is a bit hard to see. Low priority but if it turns out to be an easy fix would be much appreciated.
![chrome_iGmpEGGxyb](https://user-images.githubusercontent.com/13005453/180644831-80eb5e75-dabc-4210-ba0c-0ade1c5ce378.gif)

**Comment by blyad2137** [comment]
Tought I checked that, when I'll be back home I will check this out, thanks for letting me know-how.

**Comment by rokibhasansagar** [comment]
Google changed color codes, again 😞 
Thus, the previous problem is back.

**Comment by blyad2137** [comment]
Just to clarify, fixed that 2 days ago in U60

**Comment by C4J3** [comment]
Though the 'Search in Drive' text still shows up grey/black any search term you enter displays correctly.

**Comment by blyad2137** [comment]
You mean placeholder.
I had to double check this because everything was working fine for me, turns out it's browser related issue.
When I checked on Edge I had to add `!important` and use `opacity:` instead of alpha value in rgba to make it translucent.

This will be pushed in next update, it's not really that of a big issue to devote update to, but if you really want it rn, here's what you need to paste somwhere in the code:
`input.gb_df::placeholder {
	color: rgba(var(--white-rgb,1)) !important;
	opacity: .4;
}`

**Comment by C4J3** [comment]
TYVM!
